<?php

namespace KalkanCrypt;
enum Error : int
{
    case KCR_OK                                =	0x00000000; //	Нет ошибки
    case KCR_ERROR_READ_PKCS12                 =	0x08F00002; //	Невозможно прочитать файл формата pkcs#12
    case KCR_ERROR_OPEN_PKCS12                 =	0x08F00003; //	Невозможно открыть файл формата pkcs12
    case KCR_INVALID_PROPID                    =	0x08F00004; //	Недопустимый идентификатор расширения сертификата
    case KCR_BUFFER_TOO_SMALL                  =	0x08F00005; //	Размер буфера слишком мал
    case KCR_CERT_PARSE_ERROR                  =	0x08F00006; //	Невозможно разобрать (распарсить) сертификат
    case KCR_INVALID_FLAG                      =	0x08F00007; //	Недопустимый флаг
    case KCR_OPENFILEERR                       =	0x08F00008; //	Невозможно открыть файл
    case KCR_INVALIDPASSWORD                   =	0x08F00009; //	Неправильный пароль
    case KCR_MEMORY_ERROR                      =	0x08F0000d; //	Невозможно выделить память
    case KCR_CHECKCHAINERROR                   =	0x08F0000e; //	Не найден сертификат УЦ или сертификат пользователя при проверки цепочки
    case KCR_VALIDTYPEERROR                    =	0x08F00010; //	Недопустимый тип валидации сертификата
    case KCR_BADCRLFORMAT                      =	0x08F00011; //	Некорректный формат CRL
    case KCR_LOADCRLERROR                      =	0x08F00012; //	Невозможно загрузить CRL
    case KCR_LOADCRLSERROR                     =	0x08F00013; //	Невозможно загрузить CRL-ы
    case KCR_UNKNOWN_ALG                       =	0x08F00015; //	Неизвестный алгоритм подписи
    case KCR_KEYNOTFOUND                       =	0x08F00016; //	Не найден приватный ключ пользователя
    case KCR_SIGN_INIT_ERROR                   =	0x08F00017; //	Невозможно инициализировать менеджера подписи
    case KCR_SIGN_ERROR                        =	0x08F00018; //	Не удалось сгенерировать цифровую подпись
    case KCR_ENCODE_ERROR                      =	0x08F00019; //	Ошибка шифрования
    case KCR_INVALID_FLAGS                     =	0x08F0001a; //	Недопустимые флаги
    case KCR_CERTNOTFOUND                      =	0x08F0001b; //	Не найден сертификат пользователя
    case KCR_VERIFYSIGNERROR                   =	0x08F0001c; //	Ошибка верификации подписи xml
    case KCR_BASE64_DECODE_ERROR               =	0x08F0001d; //	Ошибка дешифровки из Base 64
    case KCR_UNKNOWN_CMS_FORMAT                =	0x08F0001e; //	Неизвестный формат CMS
    case KCR_GETHASHERROR                      =	0x08F0001f; //	Не удалось хэшировать данные
    case KCR_CA_CERT_NOT_FOUND                 =	0x08F00020; //	Не найден сертификат УЦ
    case KCR_XMLSECINIT_ERROR                  =	0x08F00021; //	Ошибка инициализации xmlsec
    case KCR_LOADTRUSTEDCERTSERR               =	0x08F00022; //	Ошибка загрузки доверенных сертификатов
    case KCR_SIGN_INVALID                      =	0x08F00023; //	Недопустимая подпись xml
    case KCR_NOSIGNFOUND                       =	0x08F00024; //	Не найдена подпись во входных данных
    case KCR_DECODE_ERROR                      =	0x08F00025; //	Ошибка дешифрования
    case KCR_XMLPARSEERROR                     =	0x08F00026; //	Невозможно разобрать (распарсить) xml
    case KCR_XMLADDIDERROR                     =	0x08F00027; //	Не удалось добавить атрибут ID
    case KCR_XMLINTERNALERROR                  =	0x08F00028; //	Ошибка при работе с xml
    case KCR_XMLSETSIGNERROR                   =	0x08F00029; //	Не удалось подписать xml
    case KCR_OPENSSLERROR                      =	0x08F0002a; //	Ошибка openssl
    case KCR_NOTOKENFOUND                      =	0x08F0002c; //	Не найден токен
    case KCR_OCSP_ADDCERTERR                   =	0x08F0002d; //	Не удалось добавить сертификат в ocsp
    case KCR_OCSP_PARSEURLERR                  =	0x08F0002e; //	Не удалось разобрать url
    case KCR_OCSP_ADDHOSTERR                   =	0x08F0002f; //	Не удалось добавить хост
    case KCR_OCSP_REQERR                       =	0x08F00030; //	Не удалось добавить текущее время в запрос
    case KCR_OCSP_CONNECTIONERR                =	0x08F00031; //	Ошибка подключения к OCSP респондеру
    case KCR_VERIFY_NODATA                     =	0x08F00032; //	Нет входных данных для верификации
    case KCR_IDATTR_NOTFOUND                   =	0x08F00033; //	Не найден атрибут ID
    case KCR_IDRANGE                           =	0x08F00034; //	Некорректный идентификатор
    case KCR_READERNOTFOUND                    =	0x08F00037; //	Не найден ридер
    case KCR_GETCERTPROPERR                    =	0x08F00038; //	Не удалось получить значение атрибута
    case KCR_SIGNFORMMAT                       =	0x08F00039; //	Неизвестный формат подписи
    case KCR_INDATAFORMAT                      =	0x08F0003a; //	Неизвестный формат входных данных
    case KCR_OUTDATAFORMAT                     =	0x08F0003b; //	Неизвестный формат выходных данных
    case KCR_VERIFY_INIT_ERROR                 =	0x08F0003c; //	Невозможно инициализировать менеджера верификации подписи
    case KCR_VERIFY_ERROR                      =	0x08F0003d; //	Не удалось верифицировать цифровую подпись
    case KCR_HASH_ERROR                        =	0x08F0003e; //	Не удалось хэшировать данные
    case KCR_SIGNHASH_ERROR                    =	0x08F0003f; //	Не удалось подписать хэшированные данные
    case KCR_CACERTNOTFOUND                    =	0x08F00040; //	Не найден сертификат УЦ в хранилище сертификатов
    case KCR_CERTTIMEINVALID                   =	0x08F00042; //	Срок действия сертификата истек либо еще не наступил
    case KCR_CONVERTERROR                      =	0x08F00043; //	Ошибка записи сертификата в структуру X509
    case KCR_TSACREATEQUERY                    =	0x08F00044; //	Ошибка генерации запроса timestamp
    case KCR_CREATEOBJ                         =	0x08F00045; //	Ошибка записи OID в ASN1 структуру
    case KCR_CREATENONCE                       =	0x08F00046; //	Ошибка генерации уникального числа
    case KCR_HTTPERROR                         =	0x08F00047; //	Ошибка протокола http
    case KCR_CADESBES_FAILED                   =	0x08F00048; //	Ошибка проверки расширения CADESBES в CMS
    case KCR_CADEST_FAILED                     =	0x08F00049; //	Ошибка проверки подписи токена TSA
    case KCR_NOTSATOKEN                        =	0x08F0004a; //	В подписи не присутствует метка TSA
    case KCR_INVALID_DIGEST_LEN                =	0x08F0004b; //	Неправильная длина хэша
    case KCR_GENRANDERROR                      =	0x08F0004c; //	Ошибка генерации случайного числа
    case KCR_SOAPNSERROR                       =	0x08F0004d; //	Не найдены заголовки SOAP-сообщений
    case KCR_GETPUBKEY                         =	0x08F0004e; //	Ошибка экспорта публичного ключа
    case KCR_GETCERTINFO                       =	0x08F0004f; //	Ошибка получения информации о сертификате
    case KCR_FILEREADERROR                     =	0x08F00050; //	Ошибка чтения файла
    case KCR_CHECKERROR                        =	0x08F00051; //	Хэш не совпадает
    case KCR_ZIPEXTRACTERR                     =	0x08F00052; //	Невозможно открыть архив
    case KCR_NOMANIFESTFILE                    =	0x08F00053; //	Не найден MANIFEST
    case KCR_VERIFY_TS_HASH                    =	0x08F00054; //	не удалось проверить Хэш подписи TS
    case KCR_XADEST_FAILED                     =	0x08F00055; //	XAdES-T: Ошибка проверки подписи
    case KCR_OCSP_RESP_STAT_MALFORMEDREQUEST   =	0x08F00056; //	Неправильный запрос
    case KCR_OCSP_RESP_STAT_INTERNALERROR      =	0x08F00057; //	Внутренняя ошибка
    case KCR_OCSP_RESP_STAT_TRYLATER           =	0x08F00058; //	Попробуйте позже
    case KCR_OCSP_RESP_STAT_SIGREQUIRED        =	0x08F00059; //	Должны подписать запрос
    case KCR_OCSP_RESP_STAT_UNAUTHORIZED       = 	0x08F0005a; //	Запрос не авторизован
    case KCR_VERIFY_ISSUERSERIALV2             =	0x08F0005b; //	не удалось проверить IssuerSerialV2 в XAdES
    case KCR_OCSP_CHECKCERTFROMRESP            =	0x08F0005c; //	Ошибка проверки сертификата OCSP-респондера
    case KCR_CRLEXPIRED                        =	0x08F0005d; //	CRL-файл просрочен
    case KCR_LIBRARYNOTINITIALIZED             =	0x08F00101; //	Библиотека не инициализирована
    case KCR_ENGINELOADERR                     =	0x08F00200; //	Ошибка подключения (загрузки) модуля (engine)
    case KCR_PARAM_ERROR                       =	0x08F00300; //	Некорректные входные данные
    case KCR_CERT_STATUS_OK                    =	0x08F00400; //	Статус сертификата – валидный. Используется при проверке сертификата по OCSP. (не является ошибкой, делается запись в лог)
    case KCR_CERT_STATUS_REVOKED               =	0x08F00401; //	Статус сертификата – отозван. Используется при проверке сертификата по OCSP.
    case KCR_CERT_STATUS_UNKNOWN               =	0x08F00402; //	Статус сертификата – неизвестен. Используется при проверке сертификата по OCSP. Например, не удалось установить издателя сертификата.
}