name: PhpUnit

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Copy kalkancrypt.so to project root
        run: cp ~/projects/kalkan-crypt/kalkancrypt.so.82nts ./kalkancrypt.so.82nts

      - name: Build docker image
        run: make build

      - name: Install dependencies
        run: make composer_install

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run test suite base
        run: |
          make test > test.log && \
          cat test.log

      - name: Run test suite sys_has_reg_certs
        run: |
          make test-with-certs > test-with-certs.log && \
          cat test-with-certs.log

      - name: Run test suite performance
        run: |
          make test-perf > test-perf.log && \
          cat test-perf.log

      - uses: actions/upload-artifact@v3
        with:
          name: Tests_logs
          path: |
            ./test.log
            ./test-perf.log
            ./test-with-certs.log
